report: "/mnt/dados/DashCam/Converted/report.xlsx"
gpsdata: "/mnt/dados/DashCam/Origin/GPSdata/"

convert:
  front:
    srcpath: "/mnt/dados/DashCam/Origin/VIDEO_F"
    dstpath: "/mnt/dados/DashCam/Converted/Front"
    preset: "Very Fast 2160p60 4K HEVC"
    cam: "Front"
  front_lock:
    srcpath: "/mnt/dados/DashCam/Origin/VIDEO_F_LOCK"
    dstpath: "/mnt/dados/DashCam/Converted/Front"
    preset: "Very Fast 2160p60 4K HEVC"
    cam: "Front"
  back:
    srcpath: "/mnt/dados/DashCam/Origin/VIDEO_B"
    dstpath: "/mnt/dados/DashCam/Converted/Back"
    preset: "Very Fast 1080p30"
    cam: "Back"
  back_lock:
    srcpath: "/mnt/dados/DashCam/Origin/VIDEO_B_LOCK"
    dstpath: "/mnt/dados/DashCam/Converted/Back"
    preset: "Very Fast 1080p30"
    cam: "Back"

backup:
  Front:
    compress: True
    srcpath: "/mnt/dados/DashCam/Converted/Front"
    dstpath: "/mnt/dados/DashCam/backup"
    limit: 30
  Back:
    compress: True
    srcpath: "/mnt/dados/DashCam/Converted/Back"
    dstpath: "/mnt/dados/DashCam/backup"
    limit: 30

